/* eslint-disable @next/next/no-img-element */
import { ImageResponse } from 'next/server'
import { PREFS } from '@/lib/japanPrefs'

// Edgeで動かす
export const runtime = 'edge'

// 列挙：0=なし,1=行きたい,2=行った,3=住んだ
const COLORS = {
  0: '#F7F7F7',
  1: '#f59e0b', // want
  2: '#3b82f6', // visited
  3: '#ef4444', // lived
} as const

const decodeEnum = (b64: string): number[] => {
  try {
    const bin = atob(b64)
    const bytes = Array.from(bin, ch => ch.charCodeAt(0))
    const vals: number[] = []
    for (const byte of bytes) {
      for (let shift = 6; shift >= 0 && vals.length < 47; shift -= 2) {
        vals.push((byte >> shift) & 0b11)
      }
    }
    // 必ず47件に揃える
    while (vals.length < 47) vals.push(0)
    return vals.slice(0, 47)
  } catch {
    return Array(47).fill(0)
  }
}

export async function GET(_: Request, { params }: { params: { pe: string } }) {
  const vals = decodeEnum(params.pe)

  return new ImageResponse(
    (
      <div
        style={{
          width: 1200,
          height: 630,
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'space-between',
          background: 'linear-gradient(180deg,#ffffff,#f4f6f8)',
          padding: 48,
          fontFamily: 'sans-serif',
        }}
      >
        {/* Header */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
          <div>
            <div style={{ fontSize: 40, fontWeight: 700 }}>地図コレ</div>
            <div style={{ fontSize: 22, opacity: 0.7 }}>行きたい・行った・住んだ</div>
          </div>
          <div style={{ display: 'flex', gap: 16, fontSize: 20 }}>
            <LegendSwatch color={COLORS[1]} label="行きたい" />
            <LegendSwatch color={COLORS[2]} label="行った" />
            <LegendSwatch color={COLORS[3]} label="住んだ" />
          </div>
        </div>

        {/* Grid Map 6列 × 8行相当（47枠） */}
        <div
          style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(6, 1fr)',
            gap: 8,
          }}
        >
          {PREFS.map((p, i) => (
            <div
              key={p.code}
              style={{
                height: 70,
                borderRadius: 10,
                border: '2px solid #e5e7eb',
                background: COLORS[vals[i] as 0 | 1 | 2 | 3],
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                fontSize: 20,
                fontWeight: 600,
                color: '#111827',
              }}
            >
              {p.name}
            </div>
          ))}
        </div>

        {/* Footer */}
        <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 18, opacity: 0.7 }}>
          <div>share your Japan map</div>
          <div>generated by Map Builder</div>
        </div>
      </div>
    ),
    { width: 1200, height: 630 }
  )
}

function LegendSwatch({ color, label }: { color: string; label: string }) {
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
      <div style={{ width: 16, height: 16, borderRadius: 4, background: color, border: '1px solid #11182722' }} />
      <div>{label}</div>
    </div>
  )
}

