/**
 * v12-1: Reactコード生成（Props/Variants/一部Overrides対応）
 *
 * - ComponentDef から 1ファイル完結の .tsx を生成
 * - Props: boolean / text / number / color を型安全に出力
 * - Variants: もし VariantSet 相当の情報が存在すれば（def.variantSets）、discriminated union を生成（MVP）
 * - Overrides: 「visible/text/color」相当の最小限のみ、Propsにより反映（Override > Prop > Base の思想に合わせ、props側で上書き）
 * - 依存追加なし / ランタイム関数は生成ファイルに内包
 */
import type { ComponentDef, ComponentProp } from '@/types/editor'

export function generateReactTSX(def: ComponentDef) {
  const name = pascal(def.name || 'Component')
  const propsShape = buildPropsShape(def.props || [])
  const variantType = buildVariantUnion(def as any) // Optional（なければ undefined 返却）

  const code =
`/* eslint-disable */\n` +
`// v12-1: generated by UI Builder\n` +
`import * as React from 'react'\n\n` +
renderTypes(name, propsShape, variantType) +
`\n` +
renderComponent(name, def, propsShape, variantType)

  const filename = `${name}.tsx`
  return { filename, code }
}

// ===== Types =====
type PropShape = Array<{ id: string; name: string; type: 'boolean'|'text'|'number'|'color'; defaultValue?: any; targetPath?: string }>
type VariantUnion = { typeName: string; code: string } | undefined

function buildPropsShape(props: ComponentProp[]): PropShape {
  return props.map(p => ({
    id: p.id,
    name: safePropName(p.name),
    type: p.type,
    defaultValue: p.defaultValue,
    targetPath: p.targetPath,
  }))
}

// Optional: Variant セットから discriminated union を組み立て（MVP）
function buildVariantUnion(def: any): VariantUnion {
  const sets = def?.variantSets as undefined | Array<{ name: string; values: string[] }>
  if (!sets || !Array.isArray(sets) || sets.length === 0) return undefined
  // 直積を展開
  const keys = sets.map(s => s.name || 'Variant')
  const values = sets.map(s => (s.values || []).map(v => String(v)))
  const combos = cartesian(values)
  const typeName = 'Variant'
  const members = combos.map(arr => {
    const fields = arr.map((v, i) => `${quoteKey(keys[i])}: '${escapeStr(v)}'`).join('; ')
    return `{ ${fields} }`
  })
  const code = `export type ${typeName} =\n  ${members.join('\n| ')}\n`
  return { typeName, code }
}

function renderTypes(name: string, props: PropShape, variant: VariantUnion | undefined) {
  const fields = props.map(p => {
    const t = p.type === 'boolean' ? 'boolean'
      : p.type === 'text' ? 'string'
      : p.type === 'number' ? 'number'
      : 'string' // color
    const optional = p.defaultValue === undefined ? '?' : '?'
    // optional: 基本はoptional、defaultは内部で補完
    return `  ${quoteKey(p.name)}${optional}: ${t}`
  })
  const extra = [
    `  /** ルート要素へ追加する className */`,
    `  className?: string`,
    `  /** ルートへ追加する style */`,
    `  style?: React.CSSProperties`,
  ]
  const typeBlock =
`export type ${name}Props = {\n${[...fields, ...extra].join('\n')}\n}\n`
  const variantBlock = variant?.code ? `\n${variant.code}` : ''
  return typeBlock + variantBlock
}

// ===== Component render =====
function renderComponent(name: string, def: ComponentDef, props: PropShape, variant: VariantUnion | undefined) {
  const propDefaultsLines: string[] = []
  for (const p of props) {
    if (p.defaultValue !== undefined) {
      const dv = literalFor(p.type, p.defaultValue)
      propDefaultsLines.push(`  const ${p.name} = props.${p.name} ?? ${dv}`)
    } else {
      propDefaultsLines.push(`  const ${p.name} = props.${p.name}`)
    }
  }

  const variantResolve = variant
    ? `  const variant: ${variant.typeName} | undefined = undefined // TODO: pass if you use variants\n`
    : ''

  const rootJSX = renderNodeJSX(def.root as any, 'root', props)

  return (
`export default function ${name}(props: ${name}Props) {\n` +
`${variantResolve}` +
`${propDefaultsLines.join('\n')}\n` +
`  return (\n` +
`    <div className={props.className} style={props.style} data-ui-export="${escapeAttr(def.name)}">\n` +
indent(rootJSX, 6) + `\n` +
`    </div>\n` +
`  )\n` +
`}\n\n` +
`// ===== runtime helpers (inlined) =====\n` +
`type Style = React.CSSProperties\n` +
`function cx(...xs: Array<string | false | null | undefined>) { return xs.filter(Boolean).join(' ') }\n`
  )
}

// ==== JSX emitter ====
/**
 * ざっくりルール
 * - node.type が "text" → <span> で text 表示
 * - node.type が "image" → <img> で src 表示
 * - それ以外 → <div> に style 適用
 * - targetPath がこのノード配下を指す場合、text/visible/color/number を props 経由で上書き
 */
function renderNodeJSX(node: any, path: string, props: PropShape): string {
  const type = String(node?.type ?? 'frame')
  const id = String(node?.id ?? path)
  const children: any[] = Array.isArray(node?.children) ? node.children : []
  const style = normalizeStyle(node?.style, node?.props)
  const text = (node?.props?.text ?? node?.text) as string | undefined
  const imgSrc = node?.props?.src ?? node?.props?.imageSrc
  const visible = pickVisible(node?.props)

  // collect prop overrides for this path
  const localProps = props.filter(p => p.targetPath && p.targetPath.startsWith(path))

  // build style bindings & visibility
  const styleExpr = buildStyleExpr(style, path, localProps)
  const visibleExpr = buildVisibleExpr(visible, path, localProps)

  // text binding
  const textExpr = buildTextExpr(text, path, localProps)

  // color binding (already inside styleExpr)

  // Decide tag
  if (type === 'text') {
    const ch = textExpr ?? (text != null ? jsxEscape(text) : '')
    return `<span data-id="${escapeAttr(id)}"${styleExpr}${visibleExpr}>${ch}</span>`
  }
  if (type === 'image') {
    const srcExpr = buildImgSrcExpr(imgSrc, path, localProps)
    return `<img data-id="${escapeAttr(id)}"${srcExpr}${styleExpr}${visibleExpr} />`
  }

  // generic container
  const childrenJSX = children.map((c, i) => renderNodeJSX(c, `${path}.children[${i}]`, props)).join('\n')
  return `<div data-id="${escapeAttr(id)}"${styleExpr}${visibleExpr}>\n${indent(childrenJSX, 2)}\n</div>`
}

function buildStyleExpr(style: Record<string, any>, path: string, localProps: PropShape) {
  // apply color/number props if target matches style.*
  const lines: string[] = []
  for (const [k, v] of Object.entries(style)) {
    lines.push(`${camelCSS(k)}: ${literalStyleValue(k, v)}`)
  }
  for (const p of localProps) {
    if (!p.targetPath) continue
    const rel = p.targetPath.slice(path.length) // e.g. ".style.backgroundColor"
    if (!rel.startsWith('.')) continue
    const seg = rel.slice(1)
    if (seg.startsWith('style.')) {
      const key = seg.slice('style.'.length)
      if (p.type === 'color' || p.type === 'text' || p.type === 'number' || p.type === 'boolean') {
        lines.push(`${camelCSS(key)}: ${propExpr(p)}`)
      }
    } else if (seg === 'props.fill' && (p.type === 'color' || p.type === 'text')) {
      lines.push(`backgroundColor: ${propExpr(p)}`)
    } else if (seg === 'props.stroke' && (p.type === 'color' || p.type === 'text')) {
      lines.push(`borderColor: ${propExpr(p)}`)
    } else if (seg === 'props.radius' && p.type === 'number') {
      lines.push(`borderRadius: ${propExpr(p)}`)
    } else if (seg === 'props.opacity' && (p.type === 'number' || p.type === 'text')) {
      lines.push(`opacity: ${propExpr(p)}`)
    }
  }
  if (lines.length === 0) return ''
  return ` style={{ ${lines.join(', ')} }}`
}

function buildVisibleExpr(visibleBase: boolean | undefined, path: string, localProps: PropShape) {
  // visible <- boolean prop if mapped to *.visible / *.props.visible
  let expr: string | undefined
  for (const p of localProps) {
    if (!p.targetPath) continue
    const rel = p.targetPath.slice(path.length)
    if (!rel.startsWith('.')) continue
    const seg = rel.slice(1)
    if (seg === 'visible' || seg === 'props.visible') {
      if (p.type === 'boolean') {
        expr = `{...(${propExpr(p)} === false ? { style: { display: 'none' } } : {})}`
        break
      }
    }
  }
  if (!expr && visibleBase === false) {
    expr = `{...({ style: { display: 'none' } })}`
  }
  return expr ? ` ${expr}` : ''
}

function buildTextExpr(textBase: string | undefined, path: string, localProps: PropShape) {
  for (const p of localProps) {
    if (!p.targetPath) continue
    const rel = p.targetPath.slice(path.length)
    if (!rel.startsWith('.')) continue
    const seg = rel.slice(1)
    if (seg === 'props.text' || seg === 'text') {
      return `{${propExpr(p)} ?? ${textBase != null ? jsxString(textBase) : '""'}}`
    }
  }
  return textBase != null ? jsxEscape(textBase) : undefined
}

function buildImgSrcExpr(srcBase: string | undefined, path: string, localProps: PropShape) {
  for (const p of localProps) {
    if (!p.targetPath) continue
    const rel = p.targetPath.slice(path.length)
    if (!rel.startsWith('.')) continue
    const seg = rel.slice(1)
    if (seg === 'props.src' || seg === 'props.imageSrc' || seg === 'src') {
      return ` src={${propExpr(p)} ?? ${srcBase ? jsxString(srcBase) : 'undefined'}}`
    }
  }
  return srcBase ? ` src=${jsxString(srcBase)}` : ''
}

// ===== style normalization =====
function normalizeStyle(style: any, props: any): Record<string, any> {
  const s: Record<string, any> = {}
  const x = style ?? {}
  const p = props ?? {}
  // geometry (optional)
  if (isNum(x.width)) s.width = toPx(x.width)
  if (isNum(x.height)) s.height = toPx(x.height)
  if (isNum(x.left)) s.left = toPx(x.left)
  if (isNum(x.top)) s.top = toPx(x.top)
  if (x.position) s.position = String(x.position)
  // colors
  if (x.backgroundColor) s.backgroundColor = x.backgroundColor
  if (x.color) s.color = x.color
  if (x.borderColor) s.borderColor = x.borderColor
  if (isNum(x.borderRadius)) s.borderRadius = toPx(x.borderRadius)
  if (isNum(p.radius) && !s.borderRadius) s.borderRadius = toPx(p.radius)
  if (isNum(x.opacity)) s.opacity = Number(x.opacity)
  // padding/margin (if any)
  for (const k of ['padding','paddingTop','paddingRight','paddingBottom','paddingLeft','margin','marginTop','marginRight','marginBottom','marginLeft'] as const) {
    if (isNum((x as any)[k])) (s as any)[k] = toPx((x as any)[k])
  }
  // display
  if (x.display) s.display = String(x.display)
  return s
}

// ===== misc helpers =====
function pascal(s: string) {
  return s.replace(/[^a-zA-Z0-9]+/g, ' ')
    .trim()
    .split(/\s+/)
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join('') || 'Component'
}
function safePropName(s: string) {
  const id = s.replace(/[^a-zA-Z0-9_]/g, '_')
  return /^[a-zA-Z_]/.test(id) ? id : `p_${id}`
}
function quoteKey(k: string) {
  return /^[a-zA-Z_][a-zA-Z0-9_]*$/.test(k) ? k : JSON.stringify(k)
}
function escapeStr(s: string) {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")
}
function escapeAttr(s: string) {
  return s.replace(/"/g, '&quot;')
}
function indent(s: string, n = 2) {
  const pad = ' '.repeat(n)
  return s.split('\n').map(l => (l.length ? pad + l : l)).join('\n')
}
function isNum(v: any): v is number {
  return typeof v === 'number' && Number.isFinite(v)
}
function toPx(v: number | string) {
  if (typeof v === 'number') return `${v}px`
  return String(v)
}
function camelCSS(k: string) {
  return k.replace(/-([a-z])/g, (_,c)=>c.toUpperCase())
}
function literalFor(t: 'boolean'|'text'|'number'|'color', v: any) {
  if (t === 'boolean') return v ? 'true' : 'false'
  if (t === 'number') return String(Number(v)||0)
  // text/color
  return JSON.stringify(String(v ?? ''))
}
function jsxString(s: string) {
  return JSON.stringify(s)
}
function jsxEscape(s: string) {
  // Keep as text node (escaped by React automatically when in braces)
  return `{${jsxString(s)}}`
}
function propExpr(p: { name: string; type: string }) {
  // Props名はローカル変数に束縛済み（renderComponent）
  return p.name
}
function cartesian<T>(arrs: T[][]): T[][] {
  return arrs.reduce<T[][]>((acc, cur) => {
    if (acc.length === 0) return cur.map(x => [x])
    const out: T[][] = []
    for (const a of acc) for (const b of cur) out.push([...a, b])
    return out
  }, [])
}

function literalStyleValue(key: string, v: any): string {
  if (typeof v === 'number') {
    if (/^lineHeight$/.test(key)) return String(v)
    return `${v}px`
  }
  if (typeof v === 'string') return jsxString(v)
  return JSON.stringify(v)
}

function pickVisible(props: any): boolean | undefined {
  if (!props) return undefined
  if (typeof props.visible === 'boolean') return props.visible
  return undefined
}

